# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e50e9351e0678ce933260b0c4f9bf83c90a63e112e4582e2056d0e3b0c26287df082b9da0c94955328b3d5505a3b6aae004ce5d9c6b3c7317100cfde8de40d47

test:
  secret_key_base: b0f82976e79bf7b6bfed211177d3647398d876f670ba947bcecc6723b7436ba9ce6fa7e227c71a3b2eea171af2d782c8ce0486b64ed4420974c27af1d394e6e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
